---
title: "R Notebook"
output: html_notebook
---

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
```

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("pheatmap")
```
```{r}
library (DESeq2)
```


```{r}
set.seed(123) # Setting seed for reproducibility
matrix_data <- matrix(sample(1:100, 50, replace = TRUE), nrow = 5, ncol = 10)

# Assign column names
colnames(matrix_data) <- c('cond1', 'cond2', 'cond3', 'cond4', 'cond5', 'ctrl1', 'ctrl2', 'ctrl3', 'ctrl4', 'ctrl5')

# Assign row names
rownames(matrix_data) <- paste('gene', 1:5, sep = '')

# Compute fold change for each gene
# Calculate the mean of 'cond' columns (1:5) and 'ctrl' columns (6:10)
cond_means <- rowMeans(matrix_data[, 1:5])
ctrl_means <- rowMeans(matrix_data[, 6:10])

# Calculate fold change: cond_means / ctrl_means
fold_change <- cond_means / ctrl_means

# Add the fold_change column to the matrix_data 
result_matrix <- cbind(matrix_data, fold_change)

print(result_matrix)
```